- common/src/main/java/org/cloudfoundry/identity/uaa/web/CorsFilter.java
- common/src/main/java/org/cloudfoundry/identity/uaa/web/CorsPreFlightFilter.java
- common/src/test/java/org/cloudfoundry/identity/uaa/web/CorsFilterTests.java
- uaa/src/main/webapp/WEB-INF/web.xml
Modified CorsFilter to support XHR for whitelisted request URIs and origins.
> Modified CorsFilter to support XHR for whitelisted request URIs and origins.

- server/src/main/java/org/cloudfoundry/identity/uaa/provider/token/ClientAssertionHeaderAuthenticator.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/token/JwtBearerAssertionAuthenticationFilter.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/token/JwtBearerAssertionTokenAuthenticator.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/token/ClientAssertionHeaderAuthenticatorTest.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/token/JwtBearerAssertionTokenAuthenticatorTest.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/token/MockAssertionToken.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/token/MockClientAssertionHeader.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/token/MockPublicKeyProvider.java
- uaa/src/main/resources/uaa.yml
- uaa/src/main/webapp/WEB-INF/spring/oauth-endpoints.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/JwtBearerGrantIT.java
Signed-off-by: Irina <irina.epshteyn@ge.com>
> Added enforcement of Predix-Client-Assertion header for 2way TLS.

- model/src/main/java/org/cloudfoundry/identity/uaa/zone/Links.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LogoutIT.java
Signed-off-by: Irina <irina.epshteyn@ge.com>
> Enabled logout redirect for zones for backward compatibility with 2.7.4

- server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderConfigurator.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/ZoneAwareIdpMetadataManager.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlServiceProviderConfiguratorTest.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlTestUtils.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/ZoneAwareIdpMetadataManagerTest.java
> Fix refresh of service providers for non-default zones.

- uaa/build.gradle
- uaa/src/test/java/org/cloudfoundry/identity/uaa/acceptance/SamlLoginAT.java
Signed-off-by: Henry <henry.zhao1@ge.com>
> Add acceptance test and task.

- server/src/main/resources/spring/data-source.xml
Signed-off-by: Henry <henry.zhao1@ge.com>
> expose waitCount and size for datasource MBean/JMX

- uaa/build.gradle
Signed-off-by: Sanjeev <chopra@ge.com>
> fix javamail conflict from spring metering filter (merge for 4.0.0, do NOT merge into 3.16.0)

- build.gradle
- scripts/setupDegradedTests.sh
- server/src/main/java/org/cloudfoundry/identity/uaa/mode/degraded/DegradedModeUaaFilter.java
- uaa/build.gradle
- uaa/src/test/java/org/cloudfoundry/identity/uaa/degraded/DegradedSamlLoginTests.java
Signed-off-by: Henry <henry.zhao1@ge.com>
> Generalize degradedTests execution for local and CF

- server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/IdpMetadataGenerator.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/SamlTestUtils.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/idp/ZoneAwareIdpMetadataGeneratorTest.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginWithLocalIdpIT.java
Signed-off-by: Bharath <bharath.sekar@ge.com>
> Add support for HTTP Redirect binding for UAA as SAML IDP

- server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsTests.java
The method signature has changed upstream, causing compilation issue when cherry-picked onto rc
> fix compilation issue

- model/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZone.java
- server/src/main/java/org/cloudfoundry/identity/uaa/oauth/AntPathRedirectResolver.java
- server/src/main/java/org/cloudfoundry/identity/uaa/zone/JdbcIdentityZoneProvisioning.java
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_4_0__Add_EnableRedirectUriCheck_To_Identity_Zone.sql
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_4_0__Add_EnableRedirectUriCheck_To_Identity_Zone.sql
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/IdentityZoneEndpointsIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointsMockMvcTests.java
Signed-off-by: Arjun <arjun.nayak@ge.com>
> Added tests and implementation for enableRedirectUriCheck on a zone level

- server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java
- server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtilsTest.java
Signed-off-by: Arjun <arjun.nayak@ge.com>
> Allow star in ports for redirect uris.

- server/src/main/resources/templates/web/idp_discovery/email.html
- server/src/main/resources/templates/web/layouts/main.html
- server/src/main/resources/templates/web/layouts/pivotal-ui-main.html
- uaa/src/main/webapp/resources/predix/stylesheets/application.css
- uaa/src/main/webapp/resources/predix/stylesheets/predix-styles.css
Signed-off-by: Arjun <arjun.nayak@ge.com>
> Styled email.html with banner and new template.

- uaa/src/main/webapp/resources/predix/stylesheets/predix-styles.css
https://rally1.rallydev.com/#/59288075112/detail/defect/174835023348
> fix idp discovery page product logo warp

- uaa/slateCustomizations/source/index.html.md.erb
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointDocs.java
To view the sample docs with the new change please refer index.html file in the rally story.
> Add KeyProviderConfig api docs.

- server/src/main/resources/templates/web/layouts/pui-mfa-main.html
- server/src/main/resources/templates/web/mfa/enter_code.html
- server/src/main/resources/templates/web/mfa/manual_registration.html
- server/src/main/resources/templates/web/mfa/qr_code.html
- uaa/src/main/webapp/resources/predix/stylesheets/application.css
- uaa/src/main/webapp/resources/predix/stylesheets/mfa.css
to review:
1. uncomment mfa options in uaa.yml
1. log in as marissa koala
1. run through mfa flow with google authenticator
> predixify uaa mfa pages

- server/src/main/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioning.java
- server/src/test/java/org/cloudfoundry/identity/uaa/scim/jdbc/JdbcScimUserProvisioningTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ScimUserEndpointsIntegrationTests.java
- Defect for SQL schema information exposure on error
> Defect for SQL schema information exposure on error

- server/src/main/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtils.java
- server/src/test/java/org/cloudfoundry/identity/uaa/util/UaaUrlUtilsTest.java
Signed-off-by: Arjun <Arjun.Nayak@ge.com>
> add port wildcard from feature/support_custom_redirect_uri_schemes

- server/src/main/resources/spring/login-ui.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LogoutIT.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
Signed-off-by: Arjun <arjun.nayak@ge.com>
> Reinstate /logout endpoint for backward compatibility.

- server/build.gradle
- uaa/build.gradle
Signed-off-by: Brittany <brittany.johnson@ge.com>
> Exclude jackson dependencies from log filter.

- Jenkinsfile
- PPCDeployJenkinsfile
Changing Jenkins file to add manifest creation
> Adding manifest file

- server/build.gradle
- server/src/main/java/org/cloudfoundry/identity/uaa/oauth/AntPathRedirectResolver.java
- server/src/test/java/org/cloudfoundry/identity/uaa/oauth/AntPathRedirectResolverTests.java
- uaa/build.gradle
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
Fixes DE53008 - Partial Open-Redirect in UAA via Subdomains Inclusion
> Feature/redirect should not check subdomain 4.30.0

- server/build.gradle
- server/src/main/java/org/cloudfoundry/identity/uaa/oauth/AntPathRedirectResolver.java
- server/src/test/java/org/cloudfoundry/identity/uaa/oauth/AntPathRedirectResolverTests.java
- uaa/build.gradle
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/token/TokenMvcMockTests.java
> Revert "Feature/redirect should not check subdomain 4.30.0"

- build.gradle
**Story**: [US435530](https://rally1.rallydev.com/#/detail/userstory/410715018988/tasks?fdp=true): Persist changes made to release dockerized version of UAA 4.30.0 for future release
**Task**: Persist using build.ge artifactory and predix-virtual in predix_prunes/jwt_grant_4.30.0
> [US435530]: Persist changes made to release dockerized version of UAA 4.30.0

- DeployGovCloudJenkinsfile
- DeployJenkinsfile
- DocsJenkinsfile
- Jenkinsfile
- PPCDeployJenkinsfile
- PublishBintrayJenkinsfile
- build.gradle
- gradle.properties
- scripts/setup-tests.sh
- server/build.gradle
- server/src/main/java/org/cloudfoundry/identity/uaa/db/CloudDataSourceConfig.java
- server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/UaaConfiguration.java
- server/src/main/resources/spring/data-source.xml
[US453191](https://rally1.rallydev.com/#/detail/userstory/449839422644?fdp=true): [UAA] Create a branch for CI customization and cherry-pick commits from predix_extensions_4.30.0
Successful Upload to Artifactory: https://artifactory.build.ge.com/webapp/#/artifacts/browse/tree/General/MAAXA/builds/uaa/74.27.0/cloudfoundry-identity-uaa-74.27.0.war
Successful Build w/ Unit, MockMvc, Integration Tests: https://i.ci.build.ge.com/bjmjek1k/ci/job/UAA/job/Build%20n%20Test/job/predix_ci_customizations/133/
Successful Deploy to release-candidate: 
https://i.ci.build.ge.com/bjmjek1k/ci/job/UAA/job/Deploy/job/predix_ci_customizations/56/
> [US453191] Predix CI Customizations Branch

- DeployJenkinsfile
- Jenkinsfile
- scripts/setup-tests.sh
[US463082](https://rally1.rallydev.com/#/435415209676d/iterationstatus?detail=%2Fuserstory%2F469197832776&view=ca9cd7bc-545a-45d3-ae00-8df607aeea4d&fdp=true?fdp=true): [UAA] PR for pipeline fixes onto ci_pipelines branch
(Covers syncing UAA upgrade branch with changes covered in: [US381511](https://rally1.rallydev.com/#/435415209676d/iterationstatus?detail=%2Fuserstory%2F343940370860&view=ca9cd7bc-545a-45d3-ae00-8df607aeea4d))
Successful build & test: https://i.ci.build.ge.com/bjmjek1k/ci/job/UAA/job/Build%20n%20Test/job/update-ci-pipelines/2/
Successful deploy: https://i.ci.build.ge.com/bjmjek1k/ci/job/UAA/job/Deploy/job/update-ci-pipelines/2/
> [US463082] Pipeline fixes

- gradle.properties
- server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
- server/src/main/java/org/cloudfoundry/identity/uaa/web/LimitedModeUaaFilter.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/util/MockMvcUtils.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/performance/LoginPagePerformanceMockMvcTest.java
[US472744](https://rally1.rallydev.com/#/435415209676d/iterationstatus?detail=%2Fuserstory%2F499176589512&fdp=true?fdp=true): [UAA] Bring in changes for IDP db calls to 4.30.0
Upstream PR: https://github.com/cloudfoundry/uaa/pull/1441
> [US472744]: Optimize IdP requests to database on login

- server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/oauth/XOAuthProviderConfigurator.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/SamlIdentityProviderConfigurator.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/saml/SamlIdentityProviderConfiguratorTests.java
[US476033](https://rally1.rallydev.com/#/435415209676d/iterationstatus?detail=%2Fuserstory%2F505904453824&fdp=true?fdp=true): [UAA] Investigate & implement login page perf improvements
> [US476033] optimize login database requests

- server/src/main/java/org/cloudfoundry/identity/uaa/web/UaaLogFilter.java
- server/src/test/java/org/cloudfoundry/identity/uaa/web/UaaLogFilterTest.java
- uaa/src/main/webapp/WEB-INF/spring-servlet.xml
Added distributed log tracing.
> Fix missing correlation ID in log messages

- model/src/main/java/org/cloudfoundry/identity/uaa/oauth/jwk/JsonWebKeyDeserializer.java
- server/src/main/java/org/cloudfoundry/identity/uaa/authentication/manager/DynamicLdapAuthenticationManager.java
- server/src/main/java/org/cloudfoundry/identity/uaa/codestore/JdbcExpiringCodeStore.java
- server/src/main/java/org/cloudfoundry/identity/uaa/cypto/EncryptionService.java
- server/src/main/java/org/cloudfoundry/identity/uaa/invitations/InvitationsController.java
- server/src/main/java/org/cloudfoundry/identity/uaa/login/TotpMfaEndpoint.java
First set of fixes for high/medium impact issues found by Coverity
> Fix high/medium coverity issues - Part I

- server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaAuthorizationEndpoint.java
- server/src/main/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenStore.java
- server/src/main/java/org/cloudfoundry/identity/uaa/oauth/refresh/RefreshTokenCreator.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpoints.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/ldap/PasswordComparisonAuthenticator.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/IdpInitiatedLoginController.java
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/idp/NonSnarlIdpMetadataManager.java
- server/src/main/java/org/cloudfoundry/identity/uaa/scim/bootstrap/ScimUserBootstrap.java
- server/src/test/java/org/cloudfoundry/identity/uaa/provider/IdentityProviderEndpointsTest.java
Second set of fixes for high/medium impact issues found by Coverity. Continuation of https://github.com/GESoftware-CF/uaa/pull/266
> Fix high/medium coverity issues - Part II

- Dockerfile
- DockerizeJenkinsfile
- dependencies.gradle
- docker.gradle
- uaa/build.gradle
- uaa/src/main/resources/uaa-docker.yml
This is for merging Dockerize pipeline fixes from the predix_extensions_75.6.0 branch (see https://github.com/GESoftware-CF/uaa/pull/347) and the predix_prunes/jwt_grant_75.6.0 branches (https://github.com/GESoftware-CF/uaa/commit/034223931b97a65c6e62834efa74ee2e8e9edd4b) into rc_75.6.0
> Merge predix extensions 75.6.0 and predix_prunes/jwt_grant_75.6.0 with dockerized UAA pipeline fixes into rc_75.6.0

- uaa/src/test/java/org/cloudfoundry/identity/uaa/acceptance/JwtBearerGrantAT.java
Assertion token is provided to UAA for authentication using JWT Bearer
grant flow. Access token is a token issued by UAA in exchange for the
assertion token after successful assertion token validation.
When assertion token is validated, its audience claim is compared to
the request URL. When access token is issued, its issuer claim is set
to issuer URI from uaa.yml config. JwtBearerGrantAT assumed that
audience and issuer are always the same. However, currently, for the
UAA deployment in AWS EKS, token request URL is set to a temporary
route [1] while token issuer is set to UAA route in CloudFoundry [2].
When DNS is setup to map UAA routes in EKS to CF routes, discrepancy
between audience of assertion token and issuer of access token should
go away.
- Add TOKEN_ISSUER_URL environment …
> Modify JwtBearerGrantAT to support a use case when assertion token audience is different from access token issuer

- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
- Added MockMvc tests to login with IDP discovery and self-service links enable/disable
> Validate self-service links during login with IDP discovery

- Jenkinsfile
- model/src/main/java/org/cloudfoundry/identity/uaa/zone/Links.java
- model/src/test/resources/org/cloudfoundry/identity/uaa/zone/SampleIdentityZone.json
- server/src/main/java/org/cloudfoundry/identity/uaa/account/AccountsController.java
- server/src/main/java/org/cloudfoundry/identity/uaa/account/ResetPasswordController.java
- server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/IdentityZoneConfigurationBootstrap.java
- server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
- server/src/test/java/org/cloudfoundry/identity/uaa/config/IdentityZoneConfigurationBootstrapTests.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/AccountsControllerTest.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerTest.java
- server/src/test/java/org/cloudfoundry/identity/uaa/zone/JdbcIdentityZoneProvisioningTests.java
- uaa/build.gradle
- uaa/src/main/resources/messages.properties
- uaa/src/main/webapp/WEB-INF/spring-servlet.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/AccountsControllerMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/util/MockMvcUtils.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointsMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/performance/LoginPagePerformanceMockMvcTest.java
- uaa/src/test/resources/integration_test_properties.yml
Merge complete implementation of split "self-service" flag from predix_extensions_75.18.1 branch into rc_75.18.1 branch
> Merge complete implementation of split "self-service" flag from predix_extensions_75.18.1 branch into rc_75.18.1 branch

- scripts/cargo/uaa.yml
- server/src/main/java/org/cloudfoundry/identity/uaa/provider/saml/NonSnarlMetadataManager.java
These commits were made along with the optimization fixes in https://github.com/GESoftware-CF/uaa/pull/463, but they belong in predix_extensions as they are generic improvements.
> Tweaks from optimize login database requests 75.18.1 branch

- uaa/src/main/webapp/WEB-INF/spring/multitenant-endpoints.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerMockMvcTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/OrchestratorZone.java
Merge Predix extensions 75.18.1 into rc_75.18.3 to deploy Zone API to EKS.
> Merge Predix extensions 75.18.1 into rc_75.18.3

- AcceptanceEKSJenkinsfile
- Adding QA ENV to UAA EKS Acceptance test Jenkins file
> Adding QA ENV to UAA EKS Acceptance test Jenkins file

- AcceptanceEKSJenkinsfile
- uaa/src/test/java/org/cloudfoundry/identity/uaa/orchestrator/OrchestratorClaimAT.java
- uaa/src/test/resources/orchestrator-integration.yml
Add UAA EKS Orchestrator Test
-The Test Creates and verifies a claim
-The Test Verifies Get Claim
-The Test Verifies Delete Claim and deletes the created claim
_Add Configuration for Environment for Dev, QA , Int, Stage ,
> Uaa orch claim test

- dependencies.gradle
- server/build.gradle
- server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/AwsSecretsLoader.java
- server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/YamlServletProfileInitializer.java
- server/src/test/java/org/cloudfoundry/identity/uaa/impl/config/AwsSecretsLoaderTest.java
Add spring aws cloud secret manager dependency to build.gradle, also add
aws sdk sts.
> Add spring secret manager dependencies

- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerMockMvcTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/ErrorMessageUtil.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
1. Fix the grammar in the error message
2. Organize the import
3. Add proper comment on import instance validation.
> Fix gaps in the import instance

- AcceptanceEKSJenkinsfile
- DeployJenkinsfile
Manage functional user credentilas in Jenkins
> Manage functional user credentials in Jenkins

- Jenkinsfile
Added downloading otel jars in the image build stage.
[US618991] [UAA] Use new OTel agent supporting Amzn-Trace-ID
https://dev.azure.com/vernova-digital/PGOG-Essentials/_workitems/edit/248079
These changes are dependent on changes to the Dockerfile done in this PR: https://github.build.ge.com/predix/iam-container-config/pull/59
That PR also contains more details, please look at it if you have any questions.
> Added downloading otel jars in the image build stage.

- gradle.properties
> Set version to 75.18.5

- uaa/src/main/webapp/resources/predix/stylesheets/predix-styles.css
Correcting color change for manual setup page to black color
> This small change for correcting key color to black for uniformness

- server/src/main/resources/templates/web/login.html
1. When Field username show is enabled css showing wrong Bg color
> removing unwanted css for button background

- gradle.properties
> set version to 75.18.6

- AcceptanceEKSJenkinsfile
- Parameterize UAA Host in Acceptance Tests Jenkins pipeline for Blue Green deployment validation against green or blue routes
[1] https://github.software.gevernova.com/pers/uaa-k8s-deploy/pull/135
> Parameterize UAA Host in Acceptance Tests Jenkins pipeline

- uaa/src/main/java/org/cloudfoundry/identity/uaa/CSPFilter.java
- uaa/src/main/webapp/WEB-INF/web.xml
To fix Bitsight findings on UAA, need to add the following csp headers [1]
[1] https://confluence.apps.gevernova.net/devspace/display/~223036055/XSS+-+CSP
> Add csp header to uaa
