- server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V2_5_5__ExtendClientAuthScopeSize.sql
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_0_9__ExtendClientAuthScopeSize.sql
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V2_5_5__ExtendClientAuthScopeSize.sql
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/mysql/V4_0_9__ExtendClientAuthScopeSize.sql
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V2_5_5__ExtendClientAuthScopeSize.sql
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_0_9__ExtendClientAuthScopeSize.sql
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/sqlserver/V4_0_9__ExtendClientAuthScopeSize.sql
1. Revert the restriction to 4000
2. Bring back the script that did type change to `TEXT` for flyway script consistency purposes, let's say we deploy `uaa` in a new environment.
> Predix/flyway scope length fix 4.4.0

- server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
When login page is loaded in multiple tabs, and when the user submits the login that is not the recent one, they are presented with CSRF error. The user can submit the form again and it will work this time, but the `form_redirect_uri` value is lost. This fix is to restore this `form_redirect_uri`
> Verify form_redirect_uri is present in model after login page reloads

- server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
- server/src/main/resources/templates/web/login.html
- server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
Unless provided in the config, the create_account link should not show up on login page
forgot password will use the value from the config or default to uaa local forgot_password
Signed-off-by: Arjun <Arjun.Nayak@ge.com>
> Create account should not have default value

- DeployGovCloudJenkinsfile
- DeployJenkinsfile
- DockerizeJenkinsfile
- DocsJenkinsfile
- Jenkinsfile
Shared lib created by Sebastian: https://github.build.ge.com/predix/security-ci-commons/blob/master/vars/nodeDetails.groovy 
To use it, you need to set up each job to pull the shared lib and then call it in the Jenkinsfile based on the env. This is helpful to have when you want to use shared values across Jenkinsfiles (e.g. govcloud deployments for uaa, dashboard, service broker, etc) For this PR, we're sharing the docker agent config.
> update jenkinsfiles to use dtr and shared lib

- server/src/main/java/org/cloudfoundry/identity/uaa/resources/jdbc/SimpleSearchQueryConverter.java
- server/src/test/java/org/cloudfoundry/identity/uaa/resources/jdbc/SimpleSearchQueryConverterTests.java
- server/src/test/java/org/cloudfoundry/identity/uaa/scim/endpoints/ScimUserEndpointsTests.java
*Note: This supersedes [this closed PR](https://github.com/GESoftware-CF/uaa/pull/125)*
```bash
$ http \
GET 'http://localhost:8080/uaa/Users?filter=external_id%20eq%20%22test-user%22' \
'Authorization':'Bearer [REDACTED]' \
'Accept':'application/json'
```
```bash
$ ./gradlew :cloudfoundry-identity-server:test \
--tests org.cloudfoundry.identity.uaa.scim.endpoints.ScimUserEndpointsTests
$ ./gradlew :cloudfoundry-identity-server:test \
--tests org.cloudfoundry.identity.uaa.resources.jdbc.SimpleSearchQueryConverterTests
```
> Allow SCIM filtering by external_id

- server/src/main/java/org/cloudfoundry/identity/uaa/audit/LoggingAuditService.java
- server/src/test/java/org/cloudfoundry/identity/uaa/audit/LoggingAuditServiceTest.java
**Summary**: Log certain audit event types at `DEBUG` level to reduce the amount of logs generated in a production environment that usu. has its log level set to `INFO` or higher.
**Changes**:
> Log whitelisted audit event types at DEBUG level

- DeployGovCloudJenkinsfile
- DeployJenkinsfile
- Jenkinsfile
- build.gradle
[US393567](https://rally1.rallydev.com/#/detail/userstory/361940107604?fdp=true): Migrate UAA/UAA Dashboard from DevCloud Artifactory to new Build.GE Artifactory
Passing Build: https://i.ci.build.ge.com/bjmjek1k/ci/job/UAA/job/Build%20n%20Test/job/update-artifactory/15/
Uploaded Artifact: https://artifactory.build.ge.com/webapp/#/artifacts/browse/tree/General/MAAXA/builds/uaa/4.30.0-test
> [US393567] Update artifactory from devcloud to build.ge

- Dockerfile
- docker.gradle
- Move Dockerfile instructions from docker.gradle into a separate Dockerfile
- Remove dockerfile instructions for removing tomcat default
web applications as they do not exist in the new base image.
- Improve UAA Dockerfile
Replace deprecated MAINTAINER instruction with LABEL
Remove unused environment variables
Replace ADD with COPY for basic copying of local files
Combines RUN instructions to reduce the number of image layers
> Upgrade base image to tomcat:9.0.37-jdk8-openjdk-slim

- DeployJenkinsfile
- DockerizeJenkinsfile
- Jenkinsfile
- scripts/setup-tests.sh
Fix UAA Jenkins failures
- moved chromedriver and ldap installation to uaa-ci-testing docker image
Successful build: https://i.ci.build.ge.com/bjmjek1k/ci/job/UAA/job/Build%20n%20Test/view/change-requests/job/PR-187/2/
> [US459522] Fix UAA pipeline failures

- AcceptanceGovCloudJenkinsfile
- AnalysisJenkinsfile
- DeployGovCloudJenkinsfile
- DeployJenkinsfile
- DocsJenkinsfile
- Jenkinsfile
- PPCDeployJenkinsfile
Current setting of 5 days for builds isn't long enough and results in
only the last build being kept in history. This makes it hard to see
when past deployments happened for instance.
Update Jenkinsfiles to change jobs to retain a maximum of 15 builds for
a maximum of 90 days.
> Update Jenkins jobs to retain 15 builds up to 90 days

- DeployJenkinsfile
After deployment, just for staging environments, the deploy job uploads
the deployed .war file to artifactory. This was broken by refactoring in
commit 0610a7b66 - scope for utility loaded was restricted to stage it
was loaded in, and so it isn't available in this separate stage to
upload artifacts.
Fix by loading the utility file again in the upload stage.
> Fix artifactory upload for deploy builds for staging environment

- DeployJenkinsfile
Since its a different stage in a different container, uaa needs to be
checked out again for loading the common utility script used to figure
out the UAA version.
> Re-fix artifactory upload after deploy to staging

- uaa/src/main/webapp/WEB-INF/spring-servlet.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/IdentityZoneCorsPolicyIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/util/IntegrationTestUtils.java
To be correctly applied, cors filter needs access to the zone
configuration. Thus, cors filter needs to be positioned after
IdentityZoneResolvingFilter in the security filter chain.
In case of zone switching, cors policy of the originating zone is
applied.
- Update servlet configuration XML to specify cors filter to be below
IdentityZoneResolvingFilter
- Add integration test to make sure cors policy specified for zones are
being enforced
- Assert zone-with-cors-policy.localhost resolves to 127.0.0.1 loopback
address to avoid test fail.
> Change filter order to fix zone cors policy enforcement

- AcceptanceGovCloudJenkinsfile
- AnalysisJenkinsfile
- DeployGovCloudJenkinsfile
- DeployJenkinsfile
- DockerizeJenkinsfile
- DocsJenkinsfile
- Jenkinsfile
- PPCDeployJenkinsfile
- PublishBintrayJenkinsfile
- dependencies.gradle
- gradle.properties
Fixes another vulnerability still present in log4j, CVE-2021-44832 [1]
- Update log4j version in dependencies.gradle to be `2.17.1`
- Update spring-log-filter version to `3.0.4`, which also has been updated
to use log4j `2.17.1` [2]
- Update uaa version in gradle.properties to bump it to `75.6.3`
[1] https://logging.apache.org/log4j/2.x/security.html
[2] https://github.com/predix/spring-log-filter/commit/7155e82c9f3c02a0bd78603eb2c213967c9a9ad4
> Update log4j version to 2.17.1

- AnalysisJenkinsfile
Using single quotes are causing parsing script to fail and incorrectly
report issue count. Fix to use double quotes instead.
> Fix parsing of coverity scan report

- uaa/src/test/java/org/cloudfoundry/identity/uaa/acceptance/JwtBearerGrantAT.java
Instead of specifying UAA URL as a combination of UAA_HOST:UAA_PORT, use
UAA_ROUTE, which is also exported by the test running script. This
simplifies things, and lets the test script pick the route if specified
in the environment. This is useful for local minikube runs, which like
local runs is tested over HTTP, but where the UAA URL does not have a
port specified, and no CF steps are needed to be executed (see
uaa-cf-release PR [1])
[1] https://github.build.ge.com/predix/uaa-cf-release/pull/58
> Update method to specify UAA URL for JWT Bearer grant tests

- uaa/build.gradle
Acceptance tests will not be run if a previous run succeeded as gradle
doesn't see any changes to the test source files, and so assumes the
tests don't need to be run. But since the test is a 'system' test, and
the system can change (e.g. new deployment), the test needs to be run
every single time regardless of there being a code change or not.
- Update acceptanceTest task to always have tests out of date by setting
`outputs.upToDateWhen` to be false.
> Fix 'UP-TO-DATE' acceptance tests not running

- gradle.properties
This is the version that contains changes for deployment to Kubernetes.
Docker images pushed by the DockerizeJenkinsfile job use this version
for tagging images [1]. So this commit makes sure that images built are
tagged with the new version.
[1] https://github.com/GESoftware-CF/uaa/blob/predix_extensions_75.18.1/DockerizeJenkinsfile#L125
> Set version to 75.18.1

- Jenkinsfile
Currently UAA branches starting with rc_ and release_ publishes
UAA artifact jar to artifactory server so trigger GE SOS
build for these branches only.
Regex is used to compare & match branch name and trigger
GE SOS build pipeline for rc and release branches. The
old regex was incorrect and was not triggering ge sos build
for eligible branches so corrected regex to trigger ge sos
build for rc and release branches.
> Update rc & release branches selector regex for GE SOS Build pipeline

- model/src/main/java/org/cloudfoundry/identity/uaa/zone/Links.java
- model/src/test/resources/org/cloudfoundry/identity/uaa/zone/SampleIdentityZone.json
- server/src/main/java/org/cloudfoundry/identity/uaa/account/AccountsController.java
- server/src/main/java/org/cloudfoundry/identity/uaa/account/ResetPasswordController.java
- server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/IdentityZoneConfigurationBootstrap.java
- server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
- server/src/test/java/org/cloudfoundry/identity/uaa/config/IdentityZoneConfigurationBootstrapTests.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/AccountsControllerTest.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerTest.java
- uaa/src/main/resources/messages.properties
- uaa/src/main/webapp/WEB-INF/spring-servlet.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/AccountsControllerMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/util/MockMvcUtils.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/performance/LoginPagePerformanceMockMvcTest.java
- uaa/src/test/resources/integration_test_properties.yml
toggle "Reset Password" and "Register User" functionality
- If "Reset Password" flag is enabled, user can see the
"Reset Password" link, and navigate to "Reset Password" screen.
If "Reset Password" flag is disabled, "Reset Password" link
is not visible.Navigate to "Reset Password" ("/forgot_password")
screen gives error screen with messsage "Self service reset
password is disabled." and rest api will return 404 http status.
- The same is applicable for ""Register User" (“/create_account”)
flag."
> Split "self-service" flag in UAA zone config to independently

- uaa/build.gradle
Fix password reset email failure due to javax.mail conflict
spring-metering-filter dependency [1] pulls in `javax.mail:mailapi`
which conflicts with `com.sun.mail:jakarta.mail` pulled in by UAA [2][3]
for sending emails.  If the `mailapi` library gets used rather than
`jakarta.mail` (seems to depend on JAR loading order and so the problem
is intermittent), the following error gets thrown when a password reset
email is tried to be sent:
java.lang.NoSuchMethodError: 'void com.sun.mail.util.TraceInputStream.<init>(java.io.InputStream, com.sun.mail.util.MailLogger)
- Fix by fixing the exclusion of `javax.mail` in the dependency
specification for spring-metering-filter in build.gradle by specifying
it as the group rather than the module
It is possible to explicitly exclude only the mailapi …
> Fix password reset email failure due to javax.mail conflict

- model/src/main/java/org/cloudfoundry/identity/uaa/zone/Links.java
- model/src/test/resources/org/cloudfoundry/identity/uaa/zone/SampleIdentityZone.json
- server/src/main/java/org/cloudfoundry/identity/uaa/account/AccountsController.java
- server/src/main/java/org/cloudfoundry/identity/uaa/account/ResetPasswordController.java
- server/src/main/java/org/cloudfoundry/identity/uaa/impl/config/IdentityZoneConfigurationBootstrap.java
- server/src/main/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpoint.java
- server/src/test/java/org/cloudfoundry/identity/uaa/config/IdentityZoneConfigurationBootstrapTests.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/AccountsControllerTest.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/LoginInfoEndpointTests.java
- server/src/test/java/org/cloudfoundry/identity/uaa/login/ResetPasswordControllerTest.java
- uaa/src/main/resources/messages.properties
- uaa/src/main/webapp/WEB-INF/spring-servlet.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/LoginIT.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/AccountsControllerMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/login/LoginMockMvcTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/util/MockMvcUtils.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/performance/LoginPagePerformanceMockMvcTest.java
- uaa/src/test/resources/integration_test_properties.yml
Reverts GESoftware-CF/uaa#414
By default self service links will be enabled unless the new self service flags are set to false explicitly. We need to update manifest files and upgrade zone configuration so that existing and new deployments work as before.
> Revert "Split "self-service" flag in UAA zone config to independently"

- model/src/main/java/org/cloudfoundry/identity/uaa/zone/Links.java
- server/src/test/java/org/cloudfoundry/identity/uaa/config/IdentityZoneConfigurationBootstrapTests.java
For "create account" and "reset password" links
-Default values are set in Links model.
-Any values set in model will be reflected back to the caller.
-As per  LoginInfoEndpoint.java#L980-L991 priority of picking up
link value for both links(/create_account, /forgot_password) is
zone settings then global settings then default.
> Set default values as "/forgot_password" in Links

- uaa/build.gradle
- uaa/src/test/java/org/cloudfoundry/identity/uaa/acceptance/JwtBearerGrantAT.java
Instead of specifying acceptance zone URL as a combination of zone subdomain, published host, and CF domain, use ACCEPTANCE_ZONE_URL, which is exported by the test running script. This simplifies test setup, and lets the test run against all local, CF and EKS environments.
- Modify JwtBearerGrantAT to read acceptance zone URL from environment variable
- Add acceptanceTest task to build.gradle to be able to execute JwtBearerGrantAT from IDE
> Fix JwtBearerGrantAT for all environments

- uaa/src/test/java/org/cloudfoundry/identity/uaa/oauth/UaaTokenServicesTests.java
MockMvc UaaTokenServicesTests currently fail if executed after BootstrapTests because unable to find expected log message. While initializing UAA context [1] BootstrapTests trigger configuration of logger context [2] from Predix customized log4j2.properties file [3]. That modifies logging context to use Predix configuration for all MockMvc tests that execute after BootstrapTests. Since the additivity for the default log appender in Predix configuration is false [4], logs are not propagated to the appender used by UaaTokenServicesTests [5] nd tests break.
- Explicitly configure logger context from log4j2-test.properties for each test of UaaTokenServicesTests to ensure consistent test results
[1] https://github.com/GESoftware-CF/uaa/blob/predix_extensions_75.18.1/uaa/src/test/java/org/cloudf …
> Use default logger context configuration in UaaTokenServicesTests

- server/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneProvisioning.java
- server/src/main/java/org/cloudfoundry/identity/uaa/zone/JdbcIdentityZoneProvisioning.java
- server/src/test/java/org/cloudfoundry/identity/uaa/zone/JdbcIdentityZoneProvisioningTests.java
- settings.gradle
- uaa/build.gradle
- uaa/src/main/resources/uaa.yml
- uaa/src/main/webapp/WEB-INF/spring/multitenant-endpoints.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/ZoneControllerIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/ZoneControllerMockMvcTests.java
- uaa/src/test/resources/integration_test_properties.yml
- zone-service/build.gradle
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/ZoneConfiguration.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/ZoneController.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/ZoneService.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/ConnectionDetails.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/Zone.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/ZoneHeader.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/ZoneRequest.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/ZoneResponse.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/ZoneServiceTests.java
Create new module for zone-service and create configurations required
for new module. Update settings.gradle to include the new module and
directory.
Add dashboard uri required in the zone response to uaa.yml for main and
integration_test_properties.yml for test. This property has to configure
for each environment.
Create controller class for zone and add get method based on
documentation [1]
Add validation and exceptions and customize the error message specific
for orchestrator zone contract.
Create a new service for zone and reuse the DAO class from identity zone
. Write a new method in identity zone dao class to fetch identity zone
by name. Reuse the exiting query and add condition for name and active.
Build the response based on the format specified in the document [1].
Update spring …
> Orchestrator zone get api

- gesos-image-build.pipeline
By default, tag for UAA docker image built by GE SOS is set to build branch name. For example, tag for image built from rc_75.18.3 branch is set to rc_75.18.3 and for image built from release_75.18.3 branch is set to release_75.18.3. Default tag name could be overwritten by IMAGE_TAG parameter of GE SSO Build pipeline
- Set default value for IMAGE_TAG parameter in gesos-image-build.pipeline to the build branch name.
> Set default tag for docker image to build branch name

- uaa/src/main/webapp/WEB-INF/spring/multitenant-endpoints.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerMockMvcTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/OrchestratorZone.java
Zones DELETE and UPDATE require zones admin or write token scopes.
Update the test case read token for get operation and write token for
delete and update operation
Also rename to adminClientSecret instead or adminSecret
Some lines are mess in OrchestratorZoneService and format it properly.
> Zone Delete and Update fix

- server/build.gradle
Remove the org.hibernate dependency, since it is a deprecated one. This is conflict with org.hibernatae.validate group and validation(NotBlank) is failing in the deployment.
Audit having the deprecated hibernate dependency and exclude it from the
build.gradle.
> Remove org.hibernate dependency

- gesos-image-build.pipeline
One of the three IPs of gesos-apikey.gecloud.io domain resolves to 3.x.x.x. That creates 3pocalypse problem [1] that cause timeouts when connecting to gesos-apikey.gecloud.io. To resolve, Propel team added gesos-apikey.gecloud.io domain to their proxy server. Route traffic to gesos-apikey.gecloud.io through proxy to avoid timeouts.
- Add proxy entries for gesos-apikey.gecloud.io domain to Jenkins /etc/hosts
[1] https://propel.ci.build.ge.com/docs/solutions/3pocalypse-solution/
This pull requested created for UAA copy of UMS (https://github.build.ge.com/predix/user-management-ci-config/pull/44)
> Use proxy for gesos-apikey.gecloud.io domain to avoid timeouts

- uaa/src/main/webapp/WEB-INF/spring/multitenant-endpoints.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerMockMvcTests.java
- zone-service/build.gradle
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneConfiguration.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneController.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceException.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/OrchestratorZone.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/OrchestratorZoneRequest.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
Reuses business logics from existing /identityzones [2]
- Added post createZone method based on documentation [1]
- Added validation and service exception and error message specific
  for orchestrator zone service and controller.
- Added steps and logics as per service-broker provisionZone
  flow. [3]
- if subdomain is not passed as request body during create zone, generated uuid is being set to id and same id to subdomain.
     - During getOrchestratorZoneDetails call, we get as updated
       response parameters as empty {}, and connection detail
       will have the generated uuid and db stored uuid as subdomain
       value.
- Updated spring security config to include orchestrator zone create API.
- Updated required qualifiers to orchestrator zone configuration.
[1] …
> Create POST API for Orchestrator contract

- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerMockMvcTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneController.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/OrchestratorErrorResponse.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
- Return error response in application/json content type
- Format with error message in "message" field as expected by Orchestrator Controller.
- Move all exception handlers into this inner class.
- Added missing empty/space check for name parameter in service
> Fix error response handling in Orchestrator Zone CRUD apis

- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneController.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
- Create orchestrator zone API return 409 Conflict on duplicate subdomain
- OrchestratorZoneController return 409 Conflict and error message "The <CUSTOM_SUBDOMAIN> name is already taken. Please use a different subdomain."
- Updated exception handling in service class to throw ZoneAlreadyExistsException
- Added return 409 Conflict in controller error handler.
> Create orchestrator zone API return conflict on duplicate subdomain

- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
SAML certificate for Orchestrator provisioned zone is generated by Bouncycastle in DER format as binary encoded certificate data. To read public key from certificate, UAA is using Bouncycastle PEM parser that expects certificate in PEM format as a charset encoded string.
Convert certificate from DER to PEM before storing to make it compatible with Bouncycastle PEM parser and to avoid DecoderException “unable to decode base64 string” when loading.
- In OrchestratorZoneService, use Java Base64 `encodeToString` instead of `Array.toString` to convert SAML certificate DER byte array into PEM compatible string. `encodeToString` converts binary array into ISO-8859-1 charset encoded string while `Array.toString` just creates a comma-delimited list of array's elements.
- Add test to validate …
> Store SAML certificate in PEM format

- model/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneEntity.java
- server/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneProvisioning.java
- server/src/main/java/org/cloudfoundry/identity/uaa/zone/JdbcIdentityZoneProvisioning.java
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/hsqldb/V4_102__Add_ochestrator_zone_table.sql
- server/src/main/resources/org/cloudfoundry/identity/uaa/db/postgresql/V4_102__Add_ochestrator_zone_table.sql
- server/src/test/java/org/cloudfoundry/identity/uaa/test/TestUtils.java
- server/src/test/java/org/cloudfoundry/identity/uaa/zone/JdbcIdentityZoneProvisioningTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerMockMvcTests.java
- zone-service/build.gradle
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneController.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
Add flyway script for postgresql and hsqldb to add orchestrator_zone table.
Create unique key for orchestrator_zone_name to ensure only one entry for an orchestrator zone
Also create unique key for identity_zone_id to make sure only one entry
for an identity_zone. there should be one-to-one mapping between
orchestrator_zone and identity_zone
create a foreign key for faster retrieval with join query.
> Enforce orchestrator name uniqueness

- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerMockMvcTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/ErrorMessageUtil.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneController.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/OrchestratorZone.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/model/OrchestratorZoneRequest.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
Orchestrator zone POST api input validation using annotations
- Add validation annotation into OrchestratorZone
  and OrchestratorZonerequest
- Handle as field validation in the OrchestratorZone data class.
- Handle as field validation in OrchestratorZoneRequest data class
- Added exception handlers in controller class
- Controller will return 400 if validation fails.
- Validation error handling message conversion as like ums evolve
- Adjust handle error messages and exceptions in Orchestrator
  Zone controller
- Added ErrorMessageUtil where all message constants, regex patterns
  and utility methods for message conversion are added.
- As request input validation are taken care using annotations in controller and model classes (OrchestratorZoneRequest and
  OrchestratorZone), removed …
> Orchestrator zone POST api input validation using annotations

- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/MockIdentityProviderProvisioning.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerTransactionRollbackTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceException.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
Since spring only rollbacks the transaction with RuntimeException and Error, OrchestratorZoneServiceException should extend the RuntimeException instead of Exception. [1]
[1] https://github.com/spring-projects/spring-framework/blob/v5.3.18/spring-tx/src/main/java/org/springframework/transaction/interceptor/DefaultTransactionAttribute.java#L186-L188
> Change RuntimeException instead of Exception

- server/src/test/java/org/cloudfoundry/identity/uaa/test/TestAccountSetup.java
- uaa/src/main/webapp/WEB-INF/spring/multitenant-endpoints.xml
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/util/IntegrationTestUtils.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/OrchestratorZoneControllerMockMvcTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneConfiguration.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- zone-service/src/test/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneServiceTests.java
- Changed the multitenant-endpoints.xml for orchestrator zone api and add additional authorities in addition to standard uaa zone authorities. For GET API : orchestrator.zones.read POST / DELETE / PUT API : orchestrator.zones.write
- Updated mockmvc tests
> Add additional authorities for orchestrator zone api

- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
- Zones created by orchestrator zone api have correct default values for signup and password fields.
- Un-commented test case asserts for the above cases
Ref Security broker IT tests:
[1] .  https://github.build.ge.com/predix/security-service-broker/blob/master/service-broker-it/src/test/java/com/ge/predix/integration/uaa/ServiceBrokerStepsDefinitions.java#L245-L246
> Add default selfservice configs in orchestrator zone api

- Jenkinsfile
Removed apt-get -qy install lsof from mock mvc test stage script
lsof means 'List Open Files'. On Linux servers,
Lsof command is used to find all files that are open by a process that is running on the server.
lists out all open files to the output console.
This command in not in use for mock mvc tests run.
Hence it is being removed from the jenkin mvc test stage script
> Remove apt-get -qy install lsof from mock mvc test script

- Jenkinsfile
- gesos-image-build.pipeline
According to GESOS support, container image name should be unique across all products onboarded with GESOS for UAA images. Container image name chosen for UAA published in ECR in DEV environment is iam-uaa. Image name chosen for UAA in STAGE environment is iam-stage-uaa.
In Jenkins, use ECR environment to make container image name unique.
- Add a parameter to gesos-image-build.pipeline to specify ECR environment to publish UAA image to. When triggering a build in GESOS, set container image name based on the environment.
- Modify Jenkins file to pass ECR environment parameter when triggering GESOS build. For rc branch trigger GESOS build for DEV environment; for release branch trigger GESOS build for STAGE environment.
> Set image name in GESOS build request based on ECR environment

- Jenkinsfile
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlBaseIT.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginForOrchestratorZoneIT.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/SamlLoginWithLocalIdpIT.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/orchestrator/uilocators/IdploginUI.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/orchestrator/uilocators/SploginUI.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/feature/orchestrator/utils/IntegrationUtilsOrchestrator.java
Add integration test for federated login through orchestrator where the SP and IDP are created with metadata integration. and create a IDP user. Provisioning the SP and IDP Zones before performing login and checking the login flow through headless chrome browser.
> Federated login test for orchestrator provisioned zone

- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
- zone-service/src/main/java/org/cloudfoundry/identity/uaa/zone/OrchestratorZoneService.java
Token key format is changed while save to database, fix the wrong format
and update the test case to make sure that token key returns correctly.
Also add the missing authority uaa.admin to zone admin.
> Fix token key issue and add uaa.admin to admin authorities

- Jenkinsfile
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/OrchestratorZoneControllerIntegrationTests.java
In testCreateZone_WithZoneConfigValidation():
- Use super admin client credentials to retrieve native zone
- Use zone admin client credentials to retrieve client details, configuration, and default identity provider configuration for new zone
- Use zone admin client to validate zone /token_key and /check_token endpoints
> Refactor OrchestratorZoneControllerIntegrationTests

- server/src/main/java/org/cloudfoundry/identity/uaa/zone/IdentityZoneEndpoints.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/integration/IdentityZoneEndpointsIntegrationTests.java
- uaa/src/test/java/org/cloudfoundry/identity/uaa/mock/zones/IdentityZoneEndpointsMockMvcTests.java
Add logic for restricting deletion of service instances from CF for instances already ported from CF to EKS. Return appropriate error message on invocation of service instance deletion request on CF. Add MockMvc tests to validate the logic.
Add integration test cases for testing the logic.
> Restrict Deletion of Ported Service instances on CF.

- build.gradle
- uaa/build.gradle
asciidoctor-gradle-plugin [1] is no longer maintained and is causing UAA compilation error:
```
> Could not resolve all artifacts for configuration ':classpath'.
> Could not find org.ysb33r.gradle:grolifant:0.10.
Searched in the following locations:
- https://repo.maven.apache.org/maven2/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.pom
- https://plugins.gradle.org/m2/org/ysb33r/gradle/grolifant/0.10/grolifant-0.10.pom
Required by:
project : > org.asciidoctor:asciidoctor-gradle-plugin:1.6.1
```
asciidoctor-gradle-plugin is removed from the upstream UAA since version 74.5.x [2]. Remove asciidoctor-gradle-pluginfrom our UAA fork to synchronize with the upstream.
[1] https://asciidoctor.org/docs/asciidoctor-gradle-plugin/
[2] https://github.com/cloudfoundry/uaa/commit/d5cf9f839d20ee5523f593 …
> Remove asciidoctor-gradle-plugin
